# -*- coding: utf-8 -*-
"""Fifa 23 EDA of Compitions .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lTvC2DsuA38oqimVCtltK-4ykXGWwYYJ
"""



"""**#Reasearch Statements**

Specifically, I'm going to perform the following tasks:

1. Exploratory Data Analysis
2. Create simple Linear Regression on those countries who have > 300 players to predict player's Wage (in Euro)
3. Create a predict function to help you easily answer the question
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
import plotly.express as px

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

"""Load Data"""

df = pd.read_csv('/content/club.csv')

"""Data Information"""

df.info()

df.describe()

df.head()

df.tail()

"""Creating Important Dataframe"""

ls = df['Competition Name'].value_counts().index.to_list()
ls1 = df['Competition Name'].value_counts().values
temp = []
temp1= []
for i in range(len(ls)):
    temp.append(ls[i])
    temp1.append(ls1[i])
dict = {'Competition Name' : temp, 'Count' : ls1}
df1 = pd.DataFrame(dict)

temp = df.groupby('Competition Name').mean()
ls = temp['Squad Size'].index.to_list()
squad = temp['Squad Size'].values
avg_age = temp['Average Age Of Players'].values
club_val = temp['Market Value Of Club In Millions(£)'].values
mv = temp['Average Market Value Of Players In Millions(£)'].values
mv18 = temp['Market Value Of Top 18 Players In Millions(£)'].values
temp = []
temp1= []
temp2 = []
temp3= []
temp4 = []
temp5 = []
for i in range(len(ls)):
    temp.append(ls[i])
    temp1.append(squad[i])
    temp2.append(avg_age[i])
    temp3.append(club_val[i])
    temp4.append(mv[i])
    temp5.append(mv18[i])
dict1 = {'Competition Name' : temp, 'Avg Squad Size' : temp1, 'Avg Age Of Players':temp2,'Avg Market Value Of ClubsIn Millions(£)' : temp3, 'Avg Market Value Of Players In Millions(£)':temp4, 'Avg Market Value Of Top 18 Players In Millions(£)':temp5}
df2 = pd.DataFrame(dict1)

"""Compition Count"""

fig = px.bar(df1, y= 'Count' ,x = 'Competition Name', color= 'Competition Name')
fig.update_layout(showlegend=False)
fig.show()

"""# **Competition Mean Stats**


The following graph shows the Average Stats Of the Competitions present in te dataset. Although the number of teams present in each competition is not same, it does help us get a clear idea of the kind of league and what type of talents and club it has to offer

This bar chart shows the average squad size in each competition - Super League 1 and Super Lig have higher squad sizes than most leagues
"""

fig = px.bar(df2, y= 'Avg Squad Size' ,x = 'Competition Name', color= 'Competition Name')
fig.update_layout(showlegend=False)
fig.show()

"""#Average market Value of leagues


This chart shows the average club value in each league - Premier League have some of the top valued players and squads trailed by LaLiga and Seria A
"""

fig = px.bar(df2, y= 'Avg Market Value Of ClubsIn Millions(£)' ,x = 'Competition Name', color= 'Competition Name')
fig.update_layout(showlegend=False)
fig.show()

"""#Average age Of Players


This charts shows the average player age in each competition - Most of the leagues have some average age of players, notable mention is Jupiler Pro League which has players with average age of 23.8 = 24 years. Youth Football :)
"""

fig = px.bar(df2, y= 'Avg Age Of Players' ,x = 'Competition Name', color= 'Competition Name')
fig.update_layout(showlegend=False)
fig.show()

"""#2D Charts

Scatter plot showing avg age of players vs player values
"""

fig = px.scatter(df2, y="Avg Age Of Players", x="Avg Market Value Of Players In Millions(£)", color="Competition Name", symbol="Competition Name")
fig.update_traces(marker_size=10)
fig.show()

"""Scatter plot showing avg squad size vs avg player value - lower squad size and higher market value means having individuals that are top atheletes"""

fig = px.scatter(df2, y="Avg Squad Size", x="Avg Market Value Of Players In Millions(£)", color="Competition Name", symbol="Competition Name")
fig.update_traces(marker_size=10)
fig.show()

"""Scatter Plot Shoing avg club value vs squad sizes"""

fig = px.scatter(df2, y="Avg Squad Size", x="Avg Market Value Of ClubsIn Millions(£)", color="Competition Name", symbol="Competition Name")
fig.update_traces(marker_size=10)
fig.show()

"""#3D Charts
3D chart shows Average Age Of Players vs Squad Size vs Average Market value Of Players
"""

fig = px.scatter_3d(df2, x='Avg Squad Size', y='Avg Age Of Players', z='Avg Market Value Of Players In Millions(£)', color='Competition Name')
fig.show()

"""#Club Value
Shows he club market value in Millions(£)
"""

fig = px.bar(df, y= 'Market Value Of Club In Millions(£)' ,x = 'Club Name', color= 'Club Name')
fig.update_layout(showlegend=False)
fig.show()

"""#Shows The Clubs' Squad Size
Squad size of the club is the number of players that the team has and can play them in the current year
"""

fig = px.bar(df, y= 'Squad Size' ,x = 'Club Name', color= 'Club Name')
fig.update_layout(showlegend=False)
fig.show()

df.columns

"""#2D Charts
Scatter Plot showing Squad Size Vs Club Value - Manchester City Got Highly rated Individuals (less squad size)
"""

fig = px.scatter(df, y="Squad Size", x="Market Value Of Club In Millions(£)", color="Club Name", symbol="Club Name")
fig.update_traces(marker_size=10)
fig.show()

"""Scatter Plot showing Average Age Of Players vs Club Value"""

fig = px.scatter(df, y="Average Age Of Players", x="Market Value Of Club In Millions(£)", color="Club Name", symbol="Club Name")
fig.update_traces(marker_size=10)
fig.show()

"""Scatter Plot showing Average Age Of Players vs Average Market Value Of Players


"""

fig = px.scatter(df, y="Average Age Of Players", x="Average Market Value Of Players In Millions(£)", color="Club Name", symbol="Club Name")
fig.update_traces(marker_size=10)
fig.show()

"""##3D Squad Size vs Market Value vs Average Age
The above graph has ploted squad in the x axis, market value of club in y and average player age in z axis. This data can be interpreted such that :-

1. more the club value, lesser the squad size and lesser the average age of players : Club may have high valued youngsters and have a team that can player for years to come
2. more the club value, lesser the squad size and more the average age of players : Club may high valued veterans or mix of old and fresh talent and have a team that has highly skilled individual with equal youth and experience
3. less the club value, more the squad size : Club has a lot of players, but none of them are of great value
4. more the club value, more the squad size : Club may have a lot of players which may include some high valued talents or not
"""

fig = px.scatter_3d(df, x='Squad Size', y='Market Value Of Club In Millions(£)', z='Average Age Of Players', color='Club Name')
fig.show()

"""##3D Squad Size vs Market Value Of Top 18 Players vs Average Age

The above graph has ploted squad in the x axis, market of top 18 players of th club in y and average player age in z axis. This data can be interpreted such that :-

1. more the market value, lesser the squad size and lesser the average age of players : Club may have high valued youngsters and have a team that can player for years to come
2. more the market value, lesser the squad size and more the average age of players : Club may high valued veterans or mix of old and fresh talent and have a team that has highly skilled individual with equal youth and experience
3. more the market value, more the average age of players : Club may have veterans which are highly valued or/ and youngsters that are highly valued
4. more the market value, less the average age of players : Club may include few high valued veterans but mostly the squad has youngsters that are highly rated and valued.
"""

fig = px.scatter_3d(df, x='Squad Size', y='Market Value Of Top 18 Players In Millions(£)', z='Average Age Of Players', color='Club Name')
fig.show()

